const JSZip = require('jszip');

async function fetchGameName(appId) {
  const url = `https://store.steampowered.com/api/appdetails?appids=${encodeURIComponent(appId)}&l=english`;

  const response = await fetch(url, {
    headers: {
      'Accept': 'application/json',
      'User-Agent': 'SteamManifestGenerator/1.0'
    }
  });

  if (!response.ok) {
    throw new Error(`Steam request failed with status ${response.status}`);
  }

  const data = await response.json();
  const appData = data?.[appId];

  if (!appData || appData.success !== true || !appData.data?.name) {
    return null;
  }

  return appData.data.name;
}

function buildLuaContent(appId, gameName) {
  const safeName = String(gameName)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"');

  return `-- Auto-generated by Steam Manifest Generator
return {
    appid = ${Number(appId)},
    name = "${safeName}"
}
`;
}

module.exports = async function handler(req, res) {
  if (req.method !== 'GET') {
    res.status(405).send('Method not allowed');
    return;
  }

  try {
    const ids = String(req.query.ids || '')
      .split(',')
      .map(s => s.trim())
      .filter(s => /^\d+$/.test(s));

    if (!ids.length) {
      res.status(400).send('No valid IDs provided');
      return;
    }

    const zip = new JSZip();
    const readmeLines = ['Steam Manifest Generator', '', 'Included games:'];
    let addedCount = 0;

    for (const appId of ids) {
      const gameName = await fetchGameName(appId);
      if (!gameName) continue;

      zip.file(`${appId}.lua`, buildLuaContent(appId, gameName));
      readmeLines.push(`- ${appId}: ${gameName}`);
      addedCount++;
    }

    if (addedCount === 0) {
      res.status(404).send('No valid games found');
      return;
    }

    zip.file('README.txt', readmeLines.join('\n'));

    const buffer = await zip.generateAsync({ type: 'nodebuffer' });

    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', 'attachment; filename="steam_manifests.zip"');
    res.status(200).send(buffer);
  } catch (error) {
    res.status(500).send(error.message || 'Internal server error');
  }
};
