const JSZip = require('jszip');

async function fetchGameName(appId) {
  const url = `https://store.steampowered.com/api/appdetails?appids=${encodeURIComponent(appId)}&l=english`;

  const response = await fetch(url, {
    headers: {
      'Accept': 'application/json',
      'User-Agent': 'SteamManifestGenerator/1.0'
    }
  });

  if (!response.ok) {
    throw new Error(`Steam request failed with status ${response.status}`);
  }

  const data = await response.json();
  const appData = data?.[appId];

  if (!appData || appData.success !== true || !appData.data?.name) {
    return null;
  }

  return appData.data.name;
}

function buildLuaContent(appId, gameName) {
  const safeName = String(gameName).replace(/\\/g, '\\\\').replace(/"/g, '\\"');

  return `-- Auto-generated by Steam Manifest Generator
return {
    appid = ${Number(appId)},
    name = "${safeName}"
}
`;
}

function buildReadme(appId, gameName) {
  return [
    'Steam Manifest Generator',
    '',
    `App ID: ${appId}`,
    `Game Name: ${gameName}`,
    '',
    'Files included:',
    `- ${appId}.lua`,
    '- README.txt'
  ].join('\n');
}

module.exports = async function handler(req, res) {
  if (req.method !== 'GET') {
    res.status(405).send('Method not allowed');
    return;
  }

  try {
    const appId = String(req.query.appId || '').trim();

    if (!/^\d+$/.test(appId)) {
      res.status(400).send('Invalid App ID');
      return;
    }

    const gameName = await fetchGameName(appId);

    if (!gameName) {
      res.status(404).send('Game not found');
      return;
    }

    const zip = new JSZip();
    zip.file(`${appId}.lua`, buildLuaContent(appId, gameName));
    zip.file('README.txt', buildReadme(appId, gameName));

    const buffer = await zip.generateAsync({ type: 'nodebuffer' });

    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${appId}.zip"`);
    res.status(200).send(buffer);
  } catch (error) {
    res.status(500).send(error.message || 'Internal server error');
  }
};